const GAMESTORE_DATA = {
    theme: "dark",
    content: [
        {
            id: 'craftsman-one-android14',
            name: 'Craftsman ONE Android 14-15',
            description: 'Versión especial de Craftsman ONE totalmente compatible con Android 14 y 15. ¡Funciona perfecto en los móviles más nuevos!',
            version: '1.1.5',
            downloadUrl: 'https://www.mediafire.com/file/5w2bbb09dsm5jpt/CRAFTSMAN_ONE_14-15_%25F0%259F%2591%25BE%25F0%259F%258E%2581.apk/file',
            imageUrl: './assets/craftsman-one.jpg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-v1',
            name: 'NEOCRAFT v1',
            description: 'La primera obra maestra de NEOMC11. Versión 1.20.12 con mejoras gráficas y optimizaciones.',
            version: '1.20.12',
            downloadUrl: 'https://www.mediafire.com/file/cxqj0b3t0syd6vi/NEOCRAFT.apk/file',
            imageUrl: './assets/1NEOCRAFT.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-demo3-skins',
            name: 'Craftsman Zero Demo 3 para Skins',
            description: 'Demo 3 de Craftsman Zero optimizada especialmente para usar skins personalizadas sin errores.',
            version: 'Demo 3 Skins',
            downloadUrl: 'https://www.mediafire.com/file/4koz7twgiqge5lu/CRAFTSMAN_ZERO_DEMO_3_FOR_SKINS_BY_NEOMC11.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'textura-output',
            name: 'Textura Output',
            description: 'Textura moderna con bordes definidos y colores vibrantes. Perfecta para construcciones épicas en 1.18+.',
            version: '1.18+',
            downloadUrl: 'https://www.mediafire.com/file/yxuie1v5m6v0khg/outcut2.mcpack/file',
            imageUrl: './assets/out.png',
            type: 'textura',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-uno',
            name: 'Craftsman UNO',
            description: 'Versión especial con temática única y mejoras exclusivas. Ideal para quienes buscan algo diferente.',
            version: '0.15.10',
            downloadUrl: 'https://www.mediafire.com/file/briwk3jkzyald7o/Craftsman_UNO.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-lte',
            name: 'NEOCRAFT LTE',
            description: 'Versión ligera y ultra optimizada de NEOCRAFT 1.21.92. Perfecta para móviles de gama baja/media.',
            version: '1.21.92 LTE',
            downloadUrl: 'https://www.mediafire.com/file/gbqt15tt1htjijv/NEOCRAFT_LTE.apk/file',
            imageUrl: './assets/6NEOCRAFT.jpeg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-115',
            name: 'Craftsman Zero 1.1.5',
            description: 'Versión estable y completa de Craftsman Zero con todas las funciones básicas y mejoras de rendimiento.',
            version: '1.1.5',
            downloadUrl: 'https://www.mediafire.com/file/vudh0hmv9mjh2tz/Cratsman+Zero+1.1.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'shader-newb-x-dragon',
            name: 'Newb X Dragon Complementary',
            description: 'Shader ultra realista con iluminación avanzada, reflejos, nubes volumétricas y agua perfecta.',
            version: 'Latest',
            downloadUrl: 'https://www.mediafire.com/file/tk98dpuu1vfdfl4/Newb_X_Dragon_ComECCE_Complementary_Reimagined_-_Android.mcpack/file',
            imageUrl: './assets/shader.jpg',
            type: 'shader',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-trial',
            name: 'Craftsman Trial',
            description: 'Versión de prueba oficial con funciones limitadas. Ideal para probar antes de instalar la completa.',
            version: '1.0.0.16',
            downloadUrl: 'https://www.mediafire.com/file/p2vj2wjczn2qf3j/Craftsman_Trial_1.0.0.16.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-trailer',
            name: 'NEOCRAFT Trailer Edition',
            description: 'Edición especial usada en los trailers oficiales. Con efectos visuales mejorados.',
            version: 'Trailer',
            downloadUrl: 'https://www.mediafire.com/file/mookw5z8qrbintj/NEOCRAFT_Trailer_Edition_mod.apk/file',
            imageUrl: './assets/2NEOCRAFT.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-navidad',
            name: 'Craftsman Zero NAVIDAD',
            description: 'Edición especial navideña con texturas de nieve, regalos y ambiente festivo.',
            version: '1.1.5 Navidad',
            downloadUrl: 'https://www.mediafire.com/file/guv0t148wko9h0i/Craftsman+Zero+Navidad.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'minecraft-bedrock-all',
            name: 'Minecraft Bedrock Todas las Versiones',
            description: 'Carpeta oficial con TODAS las versiones de Minecraft Bedrock 1.21.124+ en un solo link.',
            version: '1.21.124+',
            downloadUrl: 'https://app.mediafire.com/folder/6vzirxgmdn4r2/1.21.94+Oficial+Grissby.com',
            imageUrl: './assets/Minecraft_Bedrock.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-one-opticraft',
            name: 'Craftsman ONE - OPTICRAFT ONE',
            description: 'La versión MÁS OPTIMIZADA de Craftsman ONE. Funciona perfecto en cualquier móvil.',
            version: '1.1.5 Optimizado',
            downloadUrl: 'https://www.mediafire.com/file/2jkfza0klfxe0c9/OPTICRAFT_ONE_%25F0%259F%25A5%2594%25E2%259B%2584.apk/file',
            imageUrl: './assets/craftsman-one.jpg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-demo2',
            name: 'Craftsman Zero Demo 2 Sin Bugs',
            description: 'Demo 2 completamente corregida, sin errores ni crashes. Ideal para probar las novedades.',
            version: 'Demo 2',
            downloadUrl: 'https://www.mediafire.com/file/7ds74aevus10761/Craftsman+Zero+Demo+2+Sin+Bugs.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-as',
            name: 'NEOCRAFT AS',
            description: 'NEOCRAFT Advanced Series con mejoras visuales, nuevos bloques y optimizaciones.',
            version: 'AS V1',
            downloadUrl: 'https://www.mediafire.com/file/23a74qf7fbv9s7n/Neocraft_AS_V1.apk/file',
            imageUrl: './assets/4NEOCRAFT.jpeg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-emotes',
            name: 'Craftsman EMOTES',
            description: 'Versión especial para grabar emotes directamente desde Craftsman. Perfecta para creadores de contenido.',
            version: '1.18',
            downloadUrl: 'https://www.mediafire.com/file/1l0wno4u23when8/Craftsman_emotes.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'textura-vanilla-neo',
            name: 'Texturas Vanilla Mejoradas',
            description: 'Pack oficial de texturas vanilla mejoradas para Craftsman 1.18+ por NEOFACEMC.',
            version: '1.3',
            downloadUrl: 'https://www.mediafire.com/file/2wsc0bpel7frifo/Texturas_Vanillas_1.18.0_By_NEOFACEMC.mcpack/file',
            imageUrl: './assets/texturaa.jpg',
            type: 'textura',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-vi',
            name: 'Craftsman VI + NeoFace',
            description: 'Craftsman VI con el famoso paquete NeoFace que mejora caras y animaciones de personajes.',
            version: '1.16.20',
            downloadUrl: 'https://www.mediafire.com/file/hgi53l00ce4okrc/Craftsman+VI+1.16+NEOFACE.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'ultracraft-updates',
            name: 'Ultracraft Todas las Actualizaciones',
            description: 'Carpeta oficial con TODAS las versiones nuevas de Ultracraft desde 1.1.5. Creador: Gabito Gaming.',
            version: '1.1.5+',
            downloadUrl: 'https://www.mediafire.com/folder/h98zm2afn6tju/Updates',
            imageUrl: './assets/ultra.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-ab',
            name: 'Craftsman AB',
            description: 'Craftsman AB - Una de las versiones más estables y populares de la comunidad.',
            version: '1.19.50',
            downloadUrl: 'https://www.mediafire.com/file/ah73nfy17woyh7j/Craftsman_AB.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-old',
            name: 'NEOCRAFT Old Edition',
            description: 'La clásica y querida versión antigua de NEOCRAFT, optimizada y con mejoras.',
            version: 'Old Edition',
            downloadUrl: 'https://www.mediafire.com/file/9jc389tiz5qkcy4/NeoCraft+Old+Edition_optimized.apk/file',
            imageUrl: './assets/1NEOCRAFT.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-sin-anuncios',
            name: 'Craftsman Zero SIN ANUNCIOS',
            description: '100% sin anuncios ni interrupciones. Disfruta del juego limpio y puro.',
            version: 'Sin anuncios',
            downloadUrl: 'https://www.mediafire.com/file/0h2pdhzy9wktolw/Craftsman_zero_sin_anuncios_By_NEOMC11.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsmine',
            name: 'Craftsmine V2',
            description: 'Una de las mejores alternativas a Craftsman con gráficos mejorados y nuevos bloques.',
            version: '2.0',
            downloadUrl: 'https://www.mediafire.com/file/42lo3yruc2rh4bo/CraftMine_V2.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'shader-newb-x-legacy',
            name: 'Newb X Legacy Shader',
            description: 'Shader clásico y ligero con excelente rendimiento. Compatible con Minecraft PE 1.21+.',
            version: '1.21+',
            downloadUrl: 'https://www.mediafire.com/file/8qmz4j57gi45ekd/Newb_X_Legacy_Mcpe_1.21.mcpack.zip/file',
            imageUrl: './assets/newb.png',
            type: 'shader',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-pe',
            name: 'Craftsman PE',
            description: 'Craftsman Pocket Edition optimizado para móviles y tablets de cualquier potencia.',
            version: 'PE',
            downloadUrl: 'https://www.mediafire.com/file/r0ummjkdjinpnn1/Craftsman_Pe.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'mundo-one-block',
            name: 'One Block Survival',
            description: 'El famoso mapa One Block actualizado a la versión 1.5.9. ¡Sobrevive y construye desde un solo bloque!',
            version: '1.5.9',
            downloadUrl: 'https://www.mediafire.com/file/fwxue1q70q93ybw/One_Block_%2528Spring_to_Life%2529_v%253D1.5.9_By_DtA_MC.mcworld/file',
            imageUrl: './assets/texturaa.jpg',
            type: 'mundo',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-demo1',
            name: 'Craftsman Zero Demo 1',
            description: 'La primera demo pública del proyecto Craftsman Zero. ¡Donde todo comenzó!',
            version: 'Demo 1',
            downloadUrl: 'https://www.mediafire.com/file/k4krz1ww0299fvk/Craftsman+Zero+Demo+1.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-121',
            name: 'NEOCRAFT 1.21.92',
            description: 'NEOCRAFT completamente actualizado a la versión 1.21.92 con todos los bloques nuevos.',
            version: '1.21.92',
            downloadUrl: 'https://www.mediafire.com/file/xml11u44xavdzs6/NEOCRAFT.apk/file',
            imageUrl: './assets/5NEOCRAFT.jpeg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-117',
            name: 'Craftsman 1.17 Mod',
            description: 'Craftsman con todas las características de Minecraft 1.17 (cuevas, axolotls, cobre, etc.).',
            version: '1.17',
            downloadUrl: 'https://www.mediafire.com/file/drep2uik81qjuqm/minecraft-1-17-2_mod.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'textura-bare-bones',
            name: 'Bare Bones',
            description: 'Textura minimalista y limpia con colores más vivos. Ideal para construcciones modernas.',
            version: '1.18+',
            downloadUrl: 'https://www.mediafire.com/file/s1ridznky8rp0fn/RP_BB.mcpack/file',
            imageUrl: './assets/bare.jpg',
            type: 'textura',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-116',
            name: 'Craftsman Zero 1.16.40',
            description: 'Craftsman Zero actualizado a 1.16.40 con cuevas gigantes, montañas y todos los bloques nuevos.',
            version: '1.16.40',
            downloadUrl: 'https://www.mediafire.com/file/bdvo2pcqrp5n7g4/Craftsman+Zero+1.16.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'balioncraft-launcher',
            name: 'BalionCraft Launcher',
            description: 'Launcher oficial con versiones 0.14.3, 0.15.10 y 1.1.5 integradas. ¡Elige al instante!',
            version: 'Multi-version',
            downloadUrl: 'https://www.mediafire.com/folder/b5g5722h3gwry/BalionLauncher',
            imageUrl: './assets/balion.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-signed',
            name: 'Craftsman (Versión Firmada)',
            description: 'Versión firmada y 100% estable lista para instalar en cualquier dispositivo Android.',
            version: 'Latest',
            downloadUrl: 'https://www.mediafire.com/file/i2jyn06j46j8jur/Craftsman__signed.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'mundo-lucky-block',
            name: 'Lucky Block Race',
            description: 'Mapa multijugador de carreras con Lucky Blocks. ¡Rompe bloques y obtén items locos!',
            version: '1.18+',
            downloadUrl: 'https://www.mediafire.com/file/x1fqf8d1d76a9zn/RainbowLuckyBlockRaceV1.1.mcworld/file',
            imageUrl: './assets/texturaa.jpg',
            type: 'mundo',
            screenshots: [],
            videos: []
        },
        {
            id: 'ultracraft-10',
            name: 'Ultracraft Primera Versión',
            description: 'La primera versión oficial de Ultracraft creada por Gabito Gaming.',
            version: '1.0',
            downloadUrl: 'https://www.mediafire.com/file/jkyr6jvpal1vfl5/ULTRACRAFT_Gabito.Gaming.apk/file',
            imageUrl: './assets/ultra.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'neocraft-se',
            name: 'NEOCRAFT SE',
            description: 'NEOCRAFT Special Edition con texturas exclusivas y mejoras visuales únicas.',
            version: 'SE',
            downloadUrl: 'https://www.mediafire.com/file/d9942l6uw7whh2n/NEOCRAFT_SE.apk/file',
            imageUrl: './assets/3NEOCRAFT.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-zero-demo3-animations',
            name: 'Craftsman Zero Demo 3 con Animaciones',
            description: 'Demo 3 con animaciones avanzadas y mejoras visuales por NEOMC11.',
            version: 'Demo 3 Animations',
            downloadUrl: 'https://www.mediafire.com/file/ev9m698nl3sjjxt/CRAFTSMAN_ZERO_DEMO_3_WITH_ANIMATIONS__by_NEOMC11.apk/file',
            imageUrl: './assets/zero.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'i-see-you-now',
            name: 'I SEE YOU NOW!',
            description: 'La famosa textura que permite ver skins de amigos en Crafting and Building + texturas vanilla mejoradas.',
            version: '1.16+',
            downloadUrl: 'https://www.mediafire.com/file/ykl2qy2d62fdnaw/I_SEE_YOU%2521_by_NEOMC11.mcpack/file',
            imageUrl: './assets/isee.png',
            type: 'textura',
            screenshots: [],
            videos: ['https://youtu.be/TpIy0LwxfGA']
        },
        {
            id: 'ultracraft-111',
            name: 'Ultracraft 1.1.1 Actualizado',
            description: 'Segunda versión oficial de Ultracraft con correcciones y mejoras. Creador: Gabito Gaming.',
            version: '1.1.1',
            downloadUrl: 'https://www.mediafire.com/file/73vyix8atnk2k2f/ULTRACRAFT_%25E2%259C%2585_ACTUALIZADO_%25E2%259C%25A8_Gabito.Gaming.apk/file',
            imageUrl: './assets/ultra.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-01510-android14',
            name: 'Craftsman 0.15.10 Android 14-15',
            description: 'Versión especial de Craftsman 0.15.10 compatible con Android 13, 14 y 15.',
            version: '0.15.10',
            downloadUrl: 'https://www.mediafire.com/file/38z1flqyp7jkvwi/CRAFTSMAN_FOR_ANDROID_13-14_BY_NEOMC11.apk/file',
            imageUrl: './assets/craftsman.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'balioncraft-112',
            name: 'BalionCraft 1.12.1',
            description: 'Versión oficial y estable de BalionCraft 1.12 con todas las funciones.',
            version: '1.12.1',
            downloadUrl: 'https://www.mediafire.com/file/59f4tfpqzms4aoa/Balioncraft_1.12.1_oficial.apk/file',
            imageUrl: './assets/balion.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-0143-mod119',
            name: 'Craftsman 0.14.3 + Mod 1.19',
            description: 'Craftsman 0.14.3 con el mod completo de Minecraft 1.19 por GOBLINyt y AlexMC.',
            version: '0.14.3 + 1.19',
            downloadUrl: 'https://www.mediafire.com/file/ppotbt1nxvf8tzi/Mod_1.19_Upcade_By_GOBLINyt_y_AlexMC.apk/file',
            imageUrl: './assets/Minecraft_Mod.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'hipercraft-121',
            name: 'HyperCraft 1.21.100',
            description: 'HyperCraft actualizado a la versión oficial 1.21.100 con todos los últimos bloques.',
            version: '1.21.100',
            downloadUrl: 'https://www.mediafire.com/file/jzeipqgtevpowca/HyperCraft_signed.apk/file',
            imageUrl: './assets/hiper.png',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'gamestore-app',
            name: 'GameStore APK Oficial',
            description: '¡La tienda GameStore ahora como app! Descargas rápidas, navegación fluida y todo en tu móvil.',
            version: '1.0',
            downloadUrl: 'https://www.mediafire.com/file/22blvwo2yeaxmea/GStore.apk/file',
            imageUrl: './assets/texturaa.jpg',
            type: 'app',
            screenshots: [],
            videos: []
        },
        {
            id: 'craftsman-one-oficial',
            name: 'Craftsman ONE OFICIAL',
            description: 'La versión oficial más reciente y estable de Craftsman ONE.',
            version: 'OFICIAL',
            downloadUrl: 'https://www.mediafire.com/file/v32npfacwwl168i/CRAFTSMAN_ONE_%25F0%259F%258E%2584%25E2%259C%25A8.apk/file',
            imageUrl: './assets/craftsman-one.jpg',
            type: 'app',
            screenshots: [],
            videos: []
        }
    ],
    videos: [
        { id: "v-1", title: "I SEE YOU NOW", url: "https://www.youtube.com/embed/TpIy0LwxfGA?si=WICy3XEOVsV_YRLC", thumbnail: "./assets/miniatura1 (1).jpg" },
        { id: "v-2", title: "NEW UPDATE OF CRAFTING", url: "https://youtu.be/RdriwySSGcA?si=Lqu8u-PL2X31f12X", thumbnail: "./assets/miniatura.jpg" },
        { id: "v-3", title: "HOW LOGIN IN TO CRAFTING", url: "https://youtu.be/RdriwySSGcA?si=qCiL3p9gtPzIw00k", thumbnail: "./assets/miniatura2.jpg" }
    ]
};